defaultContentLanguage: ru
minifyOutput: true
enableRobotsTXT: true
disableKinds:
  # - section # used to generate /strikes/index.json
  - taxonomy
  - term
  - RSS

markup:
  goldmark:
    renderer:
      unsafe: true

# @refs https://gohugo.io/templates/output-formats/#output-formats
outputs:
  page:
    - html
  section:
    - json

params:
  editURL: https://github.com/russiaonfire/russiaonfire.github.io/blob/master/content/
  googleTagID: G-D9M719C20V
  email: positiveagenda@proton.me
  baseURL: /
  cdnURL: ""
  github: https://github.com/russiaonfire/russiaonfire.github.io
  preconnect: https://api.mapbox.com
  mapboxToken: pk.eyJ1IjoicG9zaXRpdmVhZ2VuZGEiLCJhIjoiY2xicGhveHBvMDRrYjNucW55Z3Fia3ZtbiJ9.4Q34UBi89V3PFYgrrKIpsA

languages:
  ru:
    flag: 🇷🇺
    description: Начиная с февраля 2022 года, в России участились возгорания, подтопления и хлопки газово-горючей смейси неизвестной природы. Данная свободная энциклопедия каталогизирует подобные случаи взрывоопасной турбулентности.
    title: RUSSIA ON FIRE
    copyright: RussiaOnFire
  en:
    flag: 🇬🇧
    description: Since February 2022, fires, explosions and sabotage have become more frequent in Russia. This open encyclopedia catalogs such cases of explosive incidents.
    title: RUSSIA ON FIRE
    copyright: RussiaOnFire
